#!/usr/bin/env bash

set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd -- "$script_dir/.." && pwd)"

branch_name="$(git -C "$repo_root" branch --show-current)"
if [[ -z "$branch_name" ]]; then
  branch_name="$(git -C "$repo_root" rev-parse --short HEAD)"
fi

cat > "$repo_root/config/local.xcconfig" <<EOF
// Generated by scripts/generate_local_xcconfig_from_branch.sh
CURRENT_PROJECT_VERSION = $branch_name
APPCENTER_SECRET = ${APPCENTER_SECRET:-}
EOF

echo "Wrote config/local.xcconfig with CURRENT_PROJECT_VERSION=$branch_name"
